repos:
  - repo: local
    hooks:
      - id: forbid-root-owned-files
        name: "Forbid root-owned files in working tree"
        entry: make check-root-files
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      # Disabled in favor of local hook that runs in Poetry env for consistency
      - id: mypy
        exclude: ^$  # match nothing
        additional_dependencies: [ "types-requests", "types-PyYAML" ]
        pass_filenames: false
        args: ["--version"]
  - repo: local
    hooks:
      - id: mypy-poetry
        name: mypy (Poetry env)
        description: Run mypy inside Poetry environment to match Makefile
        entry: poetry run mypy ai_proxy/ ai_proxy_ui/ scripts/
        language: system
        pass_filenames: false
        always_run: true
      - id: check-file-lines
        name: Check no Python file exceeds 500 lines
        description: Ensures all Python files are under 500 lines for maintainability
        entry: python scripts/analyze_code_size.py --check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: run-unit-tests
        name: Run unit tests
        description: Ensures all unit tests pass before commit
        entry: make test-unit
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
      - id: ui-lint
        name: UI lint (npm)
        description: Run frontend linting to match CI's npm run lint
        entry: bash -lc "if command -v make >/dev/null 2>&1; then make lint-ui; else npm --prefix ui run lint; fi"
        language: system
        pass_filenames: false
        always_run: true
      - id: ui-typecheck
        name: UI typecheck (npm)
        description: Run frontend type checking to match CI's npm run typecheck
        entry: bash -lc "if command -v make >/dev/null 2>&1; then make type-check-ui; else npm --prefix ui run typecheck; fi"
        language: system
        pass_filenames: false
        always_run: true
      - id: ui-e2e-tests
        name: UI E2E tests (Playwright)
        description: Run UI E2E tests to ensure critical user flows work
        entry: make test-ui-e2e
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

# End of config - add more local hooks here for extensibility
