model_mappings:
  # Default catch-all (backward compatible)
  "*": "openrouter:mistralai/mistral-small-3.2-24b-instruct:free"
  
  # Gemini models - add specific mapping for gemini-2.0-flash
  "gemini-pro": "gemini:gemini-2.0-flash-001"
  "gemini-flash": "gemini:gemini-2.0-flash-001"
  "gemini-2.0-flash": "gemini:gemini-2.0-flash-001"
  "gemini-*": "gemini:gemini-2.0-flash-001"
  
  # OpenRouter models (explicit provider) - Premium models
  "gpt-4": "openrouter:openai/gpt-4"
  "gpt-4-turbo": "openrouter:openai/gpt-4-turbo"
  "gpt-4o": "openrouter:openai/gpt-4o"
  "gpt-4o-mini": "openrouter:openai/gpt-4o-mini"
  "claude-3-opus": "openrouter:anthropic/claude-3-opus"
  "claude-3-sonnet": "openrouter:anthropic/claude-3-sonnet"
  "claude-3-haiku": "openrouter:anthropic/claude-3-haiku"
  
  # Mistral models (free and paid)
  "mistral-small": "openrouter:mistralai/mistral-small-3.2-24b-instruct:free"
  "mistral-medium": "openrouter:mistralai/mistral-medium"
  "mistral-large": "openrouter:mistralai/mistral-large"
  "mistral-nemo": "openrouter:mistralai/mistral-nemo"
  
  # DeepSeek models (popular and cheap)
  "deepseek-r1": "openrouter:deepseek/deepseek-r1"
  "deepseek-v3": "openrouter:deepseek/deepseek-v3"
  "deepseek-coder": "openrouter:deepseek/deepseek-coder"
  "deepseek-chat": "openrouter:deepseek/deepseek-chat"
  
  # Qwen models (efficient and affordable)
  "qwen-32b": "openrouter:qwen/qwen-32b-preview"
  "qwen-72b": "openrouter:qwen/qwen-72b-chat"
  "qwen-14b": "openrouter:qwen/qwen-14b-chat"
  "qwen-7b": "openrouter:qwen/qwen-7b-chat"
  
  # Microsoft Phi models (reasoning focused)
  "phi-4": "openrouter:microsoft/phi-4"
  "phi-3-medium": "openrouter:microsoft/phi-3-medium-4k-instruct"
  "phi-3-mini": "openrouter:microsoft/phi-3-mini-4k-instruct"
  
  # Popular open source models (very cheap)
  "llama-3.1-8b": "openrouter:meta-llama/llama-3.1-8b-instruct:free"
  "llama-3.1-70b": "openrouter:meta-llama/llama-3.1-70b-instruct"
  "llama-3.2-3b": "openrouter:meta-llama/llama-3.2-3b-instruct:free"
  "llama-3.2-1b": "openrouter:meta-llama/llama-3.2-1b-instruct:free"
  
  # Google models via OpenRouter
  "gemma-2-9b": "openrouter:google/gemma-2-9b-it:free"
  "gemma-2-27b": "openrouter:google/gemma-2-27b-it"
  
  # Other popular models
  "hermes-3": "openrouter:nousresearch/hermes-3-llama-3.1-405b"
  "yi-34b": "openrouter:01-ai/yi-34b-chat"
  "solar-pro": "openrouter:upstage/solar-pro-preview"
  
  # Coding-specific models
  "codestral": "openrouter:mistralai/codestral-mamba"
  "codeqwen": "openrouter:qwen/codeqwen-7b-instruct"
  "deepseek-coder-v2": "openrouter:deepseek/deepseek-coder-v2-lite-instruct"
