model_mappings:
  # Default catch-all (backward compatible)
  "*": "openrouter:mistralai/mistral-small-3.2-24b-instruct:free"
  
  # Gemini models - add specific mapping for gemini-2.0-flash
  "gemini-pro": "gemini:gemini-2.0-flash-001"
  "gemini-flash": "gemini:gemini-2.0-flash-001"
  "gemini-2.0-flash": "gemini:gemini-2.0-flash-001"
  "gemini-*": "gemini:gemini-2.0-flash-001"
  
  # OpenRouter models (explicit provider)
  "gpt-4": "openrouter:openai/gpt-4"
  "gpt-4-turbo": "openrouter:openai/gpt-4-turbo"
  "claude-3-opus": "openrouter:anthropic/claude-3-opus"
  
  # Mistral models
  "mistral-small": "openrouter:mistralai/mistral-small-3.2-24b-instruct:free"
